### ISSUE TITLE
What is the difference between cross-domain and cross-origin?

### ISSUE THREAD

**Issue by ymqy** [monsur/CORSinAction#4]
There are many references to cross-domain requests and cross-origin requests in the book

- "While the XMLHttpRequest object can be used to make either same-origin or **cross-origin requests**" in P28
- "Safety is an important factor when making **cross-domain requests**" in P9

So what is the precise definition of cross-domain and cross-origin? 

Looking forward to your reply, thanks!

**Comment by monsur** [comment]
Hi I was using those terms interchangeably, to mean the same thing. You are right that I should align on consistent terminology for future editions. Thanks for the feedback!

**Comment by ymqy** [comment]
> Hi I was using those terms interchangeably, to mean the same thing. You are right that I should align on consistent terminology for future editions. Thanks for the feedback!

Thank you for your reply, but what I want to ask is: origin includes domain, different origin does not mean different domain, so are cross-origin and cross-domain the same in terms of strict definition?

**Comment by monsur** [comment]
I suppose from that perspective, "cross-origin" would be the proper term, since "cross-domain" would be an incomplete spec to make a decision on (its missing scheme and port). This is supported by the fact that the text of the [CORS spec](https://fetch.spec.whatwg.org/) does not contain the term "cross-domain".

**Comment by ymqy** [comment]
> I suppose from that perspective, "cross-origin" would be the proper term, since "cross-domain" would be an incomplete spec to make a decision on (its missing scheme and port). This is supported by the fact that the text of the [CORS spec](https://fetch.spec.whatwg.org/) does not contain the term "cross-domain".

Thank you very much, your reply has solved my confusion
